FROM node:23
WORKDIR /client_expressjs/
COPY ./shared ./shared
COPY ./client_auth ./client_auth
RUN npm install --prefix ./shared
RUN npm install --prefix ./client_auth
EXPOSE 3000
CMD ["npm", "start","--prefix", "/client_expressjs/client_auth/"]