FROM node:23
WORKDIR /client_expressjs/
COPY ./shared ./shared
COPY ./client_manager ./client_manager
RUN npm install --prefix ./shared
RUN npm install --prefix ./client_manager
EXPOSE 3002
CMD ["npm", "start","--prefix", "/client_expressjs/client_manager/"]