FROM node:23
WORKDIR /client_expressjs/
COPY ./shared ./shared
COPY ./client_executive ./client_executive
RUN npm install --prefix ./shared
RUN npm install --prefix ./client_executive
EXPOSE 3001
CMD ["npm", "start","--prefix", "/client_expressjs/client_executive/"]